### ISSUE TITLE
AddBook page: Fill in from ozon link does not work

### ISSUE THREAD

**Issue by DarkDeny** [dreikanter/bookmarkz#2]
I tried to add new book and fiil in the form from ozon data. I pasted following link:
http://www.ozon.ru/context/detail/id/19440633/
and clicked "fill for me" button, but nothing happened.

**Comment by dreikanter** [comment]
Yep. It's not implemented yet :)

**Comment by dreikanter** [comment]
Task: #32

**Comment by dreikanter** [comment]
Book data fetching implemented.
